[
  (attrset_expression)
  (rec_attrset_expression)
  (let_attrset_expression)
  (let_expression)
  (list_expression)
  (indented_string_expression)
  (formals)
  (parenthesized_expression)
  (record_type)
  (declaration_block)
  (ambient_declaration)
  (type_alias)
  (comment)
] @fold
