// Bundler settings `cf` uses for the docs Worker (generated by `cf migrate`).
import { defineWranglerConfig } from "wrangler/experimental-config";

export default defineWranglerConfig({
  types: {
    generate: false,
  },
  assetsDirectory: "../../dist/docs",
});
