// Embed the bundled `builtins` declarations into the tynix-core library.
//
// `registry/workspace/builtins.d.tynix` is the single source of truth. This
// script renders it as a Haskell module so every tynix binary types `builtins`
// (and the global builtins such as `toString`) without any project setup.
//
//   node --experimental-strip-types ./scripts/generate-prelude.ts          # write
//   node --experimental-strip-types ./scripts/generate-prelude.ts --check  # verify
import { readFile, writeFile } from "node:fs/promises";

const sourcePath = new URL("../registry/workspace/builtins.d.tynix", import.meta.url);
const modulePath = new URL("../packages/tynix-core/src/BuiltinPrelude.hs", import.meta.url);

// Haskell string literal for one line of ASCII declaration source.
function haskellString(line: string): string {
  if (/[^\x20-\x7e]/.test(line)) {
    throw new Error(`builtins.d.tynix must be printable ASCII: ${JSON.stringify(line)}`);
  }
  return `"${line.replaceAll("\\", "\\\\").replaceAll('"', '\\"')}"`;
}

function render(source: string): string {
  const lines = source.replace(/\n$/, "").split("\n");
  // Leading-comma-free list layout, matching what fourmolu produces, so the
  // formatter and the --check mode agree.
  const items = lines.map(
    (line, index) => `${index === 0 ? "[ " : "  "}${haskellString(line)}${index === lines.length - 1 ? "" : ","}`,
  );
  return [
    "-- | GENERATED by scripts/generate-prelude.ts from",
    "-- registry/workspace/builtins.d.tynix. Do not edit by hand.",
    "module BuiltinPrelude (builtinPreludePath, builtinPreludeSource) where",
    "",
    "import Data.Text (Text)",
    "import Data.Text qualified as Text",
    "",
    "-- | Virtual path the embedded declarations are reported under.",
    "builtinPreludePath :: FilePath",
    'builtinPreludePath = "<tynix>/builtins.d.tynix"',
    "",
    "-- | Source text of the embedded `builtins` declarations.",
    "builtinPreludeSource :: Text",
    "builtinPreludeSource =",
    "  Text.pack . unlines $",
    ...items.map((item) => `    ${item}`),
    "    ]",
    "",
  ].join("\n");
}

const expected = render(await readFile(sourcePath, "utf8"));

if (process.argv.includes("--check")) {
  const actual = await readFile(modulePath, "utf8").catch(() => "");
  if (actual !== expected) {
    console.error("BuiltinPrelude.hs is out of date; run scripts/generate-prelude.ts");
    process.exit(1);
  }
  console.log("BuiltinPrelude.hs is up to date");
} else {
  await writeFile(modulePath, expected);
  console.log("wrote packages/tynix-core/src/BuiltinPrelude.hs");
}
